In [1]:
import numpy

In [1]:
# check the version
numpy.__version__

NameError: name 'numpy' is not defined

In [2]:
# import NumPy using np as an alias
import numpy as np

In [2]:
# to display all the contents of the numpy namespace
np.[TAB]

SyntaxError: invalid syntax (<ipython-input-2-24a3f2f1ed32>, line 2)

In [3]:
# to display NumPy's built-in documentation
np?

Object `np` not found.


In [25]:
# define three random arrays, a 1-dimensional, 2-dimensional, 
# and 3-dimensional array by NumPy's random number generator. 
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(4, 2, 5))  # Three-dimensional array
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]]

 [[5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]]

 [[2 0 0 4 5]
  [5 6 8 4 1]]]


In [17]:
# Each array has attributes ndim (the number of dimensions), 
#  shape (the size of each dimension), and 
#  size (the total size of the array):
# print(x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (4, 2, 5)
x3 size:  40


In [18]:
# The dtype: the data type of the array
print("dtype:", x3.dtype)

dtype: int64


In [20]:
# The itemsize lists the size (in bytes) of each array element;
# The nbytes lists the total size (in bytes) of the array:

print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 320 bytes


In [21]:
# In general, nbytes is equal to itemsize times size.

In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

5

In [10]:
# negative indice:
x1[-1]

9

In [28]:
# multi-dimensianl array:using a comma-separated tuple of indices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [29]:
x2[0,0]

3

In [30]:
x2[2,0]

1

In [31]:
x2[2,-1]

7

In [81]:
# Values can also be modified using any of the above index notation:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [82]:
x1[0] = 8.159  # this will be truncated!
x1

array([8, 0, 3, 3, 7, 9])

In [83]:
# One-dimensional subarrays
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [85]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [86]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [87]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [88]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [89]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [90]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [91]:
# Multi-dimensional subarrays
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [92]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [93]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [94]:
# subarray dimensions can even be reversed together:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [134]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [135]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [49]:
# In the case of row access, the empty slice can be omitted for a more compact syntax:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


In [50]:
# Consider our two-dimensional array from before:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [51]:
# Let's extract a 2x2 subarray from this:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [52]:
# Now if we modify this subarray, we'll see 
#  that the original array is changed! Observe:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [53]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [54]:
# copy()
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [55]:
# If we now modify this subarray, 
#  the original array is not touched:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [56]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [62]:
# Reshaping of arrays:
# to put the numbers 1 through 9 in a 3x3 grid:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
aaa = np.arange(1,10) # np.arrange() generates an array
print(aaa)

[1 2 3 4 5 6 7 8 9]


In [104]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [105]:
# row vector via newaxis
x[np.newaxis, :]?

array([[1, 2, 3]])

In [106]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [107]:
# column vector via newaxis
x[:, np.newaxis]?

array([[1],
       [2],
       [3]])

In [108]:
# concatenating:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [110]:
# concatenate more than two arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [111]:
# be used for two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [114]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)?

SyntaxError: invalid syntax (<ipython-input-114-ce4aea1fb35a>, line 2)

In [137]:
grid.shape

(2, 3)

In [140]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([grid,x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [141]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [142]:
# splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # [:3],[3,5],[5:]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [143]:
# The related functions np.hsplit and np.vsplit are similar
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [149]:
upper, lower = np.vsplit(grid, [0])
print(upper)
print(lower)

[]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [147]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
