In [2]:
import pandas as pd
import numpy as np

In [3]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [5]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [6]:
# If apply a NumPy ufunc on either of these objects, 
# the result is another Pandas object with the indices preserved.
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [7]:
# Or, for a slightly more complex calculation
np.sin(df * np.pi / 4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

In [8]:
# Example: suppose we are combining two different data sources, 
#  and find only the top three US states by area 
#  and the top three US states by population:

In [9]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [10]:
# Let's see what happens when we divide these 
#  to compute the population density:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [11]:
# The resulting array contains the union of
#   indices of the two input arrays
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [13]:
# missing number
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [14]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [15]:
# Index alignment in DataFrame
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  11  19
1   2   4

In [16]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  2  6  4
1  8  6  1
2  3  8  1

In [17]:
A + B

A     B   C
0  17.0  21.0 NaN
1   8.0  12.0 NaN
2   NaN   NaN NaN

In [19]:
# Here, fill with the mean of all values in A
#  (computed by first stacking the rows of A):
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  17.0  21.0  13.0
1   8.0  12.0  10.0
2  17.0  12.0  10.0

In [20]:
fill

9.0

In [21]:
#
A = rng.randint(10, size=(3, 4))
A

array([[9, 8, 9, 4],
       [1, 3, 6, 7],
       [2, 0, 3, 1]])

In [22]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-8, -5, -3,  3],
       [-7, -8, -6, -3]])

In [25]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -8 -5 -3  3
2 -7 -8 -6 -3

In [29]:
df.iloc[0]

Q    9
R    8
S    9
T    4
Name: 0, dtype: int64

In [39]:
# column-wise
df.subtract(df['Q'], axis=0)

Q  R  S  T
0  0 -1  0 -5
1  0  2  5  6
2  0 -2  1 -1

In [40]:
# automatically align
halfrow = df.iloc[0, ::2]
halfrow

Q    9
S    9
Name: 0, dtype: int64

In [41]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -8.0 NaN -3.0 NaN
2 -7.0 NaN -6.0 NaN

In [42]:
# Missing Data
import numpy as np
import pandas as pd
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [43]:
# dtype = object
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
60.6 ms ± 1.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
878 µs ± 61.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [44]:
# error
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [9]:
# NaN
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [6]:
# like a data virus
1 + np.nan

nan

In [7]:
0 * np.nan

nan

In [10]:
# no errors, but not always useful
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [11]:
# NaN and None
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [12]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [13]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [15]:
# detecting null values
data = pd.Series([1, np.nan, 'hello', None])

In [16]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [17]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [19]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [22]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [23]:
# remove NA
data.dropna()

0        1
2    hello
dtype: object

In [29]:
data.fillna()

0        1
1    world
2    hello
3    world
dtype: object

In [47]:
#
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [48]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [60]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [51]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [54]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [55]:
df.dropna(how='any')

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [40]:
df.dropna(axis='rows', thresh=3)

0    1  2
1  2.0  3.0  5

In [41]:
# filling null values
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [42]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [43]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [44]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [56]:
# DataFrame
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [61]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [62]:
df1=df.fillna(method='ffill', axis=1)

In [66]:
df1.fillna(method='bfill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  4.0  4.0  6.0  6.0